### ISSUE TITLE
BUG: titled displayed is outdated

### ISSUE THREAD

**Issue by mzbik** [oggy/tab-switcher#29] opened 2015-11-12 03:47 UTC
Atom 1.1.0

1. Create new file. It's called Untitled. 
2. Save file. Prompted to save and enter Foo
3. File is saved. Tab renamed to Foo
4. Call up tab-switcher. 
     * BUG: File shows up as Untitled, expected is Foo

Possible dup of #26

**Comment by oggy** [comment] 2015-12-02 10:02
Confirmed as dupe of #26, which is fixed.

**Closed by oggy** 2015-12-02 10:03 UTC
