### ISSUE TITLE
Do not reorder the tabs

### ISSUE THREAD

**Issue by arv** [oggy/tab-switcher#3] opened 2014-06-22 16:16 UTC
The position of the tabs is jumping around.

A better solution would be to override the keyboard shortcut and manage the stack of tabs.

**Comment by oggy** [comment] 2015-06-07 08:16
Closing this, as it's by design. In fact the planned direction was to do something very similar to enhanced-tabs. Reordering the tabs was way simpler, though.

**Closed by oggy** 2015-06-07 08:16 UTC
